name: CI/CD workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug

env:
  VARIABLE_NAME: my first variable
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Listing files
        run: ls -al
        
      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.27.1
        with:
          php-version: '8.2'
          extensions: pdo, pdo_sqlite, pdo_pgsql

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Display first variable
        run: echo ${{ env.VARIABLE_NAME }}
        
      - name: Use a Secret
        env:
          SUPER_SECRET: ${{ secrets.SECRET_NAME }}
        run: echo $SUPER_SECRET
        
      - name: Run tests
        run: ./vendor/bin/phpunit

      - name: Login to docker hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
